export { Home} from './Home/home'
export { Contacts } from './Contact/contact'
export { Services } from './Services/services'
export { About } from './About/about'
export { Portfolio } from './Portfolio/portfolio'
export { FAQ } from './Faq/faq'
export { Labs } from './Labs/labs'
export { NotFound } from './NotFound/notFound'
export { PrivacyPolicy } from './PrivacyPolicy/privacyPolicy'